/**
 * Model for a join code. The codes are generated by instructors and entered by new users during sign up.
 * Codes specify user role (student or preceptor) and link students to their instructor.
 */
import mongoose from 'mongoose';

const JoinCodeSchema = new mongoose.Schema({
    code: {
        type: String,
        required: [true, 'a code is required']
    },
    instructorId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'an instructor ID is required']
    },
    role: {
        type: String,
        required: [true, 'a role is required']
    }, 
    expiryDate: {
        type: Date,
        required: [true, 'an expiry date is required']
    }
}, { timestamps: true });

export default mongoose.model('JoinCode', JoinCodeSchema);
